spring:
  sql.init.mode: always
  jpa:
    defer-datasource-initialization: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:./h2-db/csvupload
    username: testuser
    password: testuser
    driverClassName: org.h2.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB